{"message":"`continue` outside of a loop","code":{"code":"E0268","explanation":"A loop keyword (`break` or `continue`) was used outside of a loop.\n\nErroneous code example:\n\n```compile_fail,E0268\nfn some_func() {\n    break; // error: `break` outside of a loop\n}\n```\n\nWithout a loop to break out of or continue in, no sensible action can be taken.\nPlease verify that you are using `break` and `continue` only in loops. Example:\n\n```\nfn some_func() {\n    for _ in 0..10 {\n        break; // ok!\n    }\n}\n```\n"},"level":"error","spans":[{"file_name":"src\\main.rs","byte_start":2964,"byte_end":2972,"line_start":58,"line_end":58,"column_start":23,"column_end":31,"is_primary":true,"text":[{"text":"            Err(_) => continue,","highlight_start":23,"highlight_end":31}],"label":"cannot `continue` outside of a loop","suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[],"rendered":"\u001b[0m\u001b[1m\u001b[38;5;9merror[E0268]\u001b[0m\u001b[0m\u001b[1m\u001b[38;5;15m: `continue` outside of a loop\u001b[0m\n\u001b[0m  \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;14m--> \u001b[0m\u001b[0msrc\\main.rs:58:23\u001b[0m\n\u001b[0m   \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;14m|\u001b[0m\n\u001b[0m\u001b[1m\u001b[38;5;14m58\u001b[0m\u001b[0m \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;14m|\u001b[0m\u001b[0m \u001b[0m\u001b[0m            Err(_) => continue,\u001b[0m\n\u001b[0m   \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;14m| \u001b[0m\u001b[0m                      \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;9m^^^^^^^^\u001b[0m\u001b[0m \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;9mcannot `continue` outside of a loop\u001b[0m\n\n"}
{"message":"`break` outside of a loop or labeled block","code":{"code":"E0268","explanation":"A loop keyword (`break` or `continue`) was used outside of a loop.\n\nErroneous code example:\n\n```compile_fail,E0268\nfn some_func() {\n    break; // error: `break` outside of a loop\n}\n```\n\nWithout a loop to break out of or continue in, no sensible action can be taken.\nPlease verify that you are using `break` and `continue` only in loops. Example:\n\n```\nfn some_func() {\n    for _ in 0..10 {\n        break; // ok!\n    }\n}\n```\n"},"level":"error","spans":[{"file_name":"src\\main.rs","byte_start":3289,"byte_end":3294,"line_start":68,"line_end":68,"column_start":13,"column_end":18,"is_primary":true,"text":[{"text":"            break;","highlight_start":13,"highlight_end":18}],"label":"cannot `break` outside of a loop or labeled block","suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[],"rendered":"\u001b[0m\u001b[1m\u001b[38;5;9merror[E0268]\u001b[0m\u001b[0m\u001b[1m\u001b[38;5;15m: `break` outside of a loop or labeled block\u001b[0m\n\u001b[0m  \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;14m--> \u001b[0m\u001b[0msrc\\main.rs:68:13\u001b[0m\n\u001b[0m   \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;14m|\u001b[0m\n\u001b[0m\u001b[1m\u001b[38;5;14m68\u001b[0m\u001b[0m \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;14m|\u001b[0m\u001b[0m \u001b[0m\u001b[0m            break;\u001b[0m\n\u001b[0m   \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;14m| \u001b[0m\u001b[0m            \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;9m^^^^^\u001b[0m\u001b[0m \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;9mcannot `break` outside of a loop or labeled block\u001b[0m\n\n"}
{"message":"aborting due to 2 previous errors","code":null,"level":"error","spans":[],"children":[],"rendered":"\u001b[0m\u001b[1m\u001b[38;5;9merror\u001b[0m\u001b[0m\u001b[1m\u001b[38;5;15m: aborting due to 2 previous errors\u001b[0m\n\n"}
{"message":"For more information about this error, try `rustc --explain E0268`.","code":null,"level":"failure-note","spans":[],"children":[],"rendered":"\u001b[0m\u001b[1m\u001b[38;5;15mFor more information about this error, try `rustc --explain E0268`.\u001b[0m\n"}
